version: '3.9'

services:
  bjsoft-website:
    build: .
    restart: unless-stopped
    networks:
      - network_public
    labels:
      - traefik.enable=true

      - traefik.http.routers.bjsoft.rule=Host(`www.bjsoft.com.br`) || Host(`bjsoft.com.br`)'
      - traefik.http.routers.bjsoft.entrypoints=websecure
      - traefik.http.routers.bjsoft.tls.certresolver=letsencryptresolver

      - traefik.http.services.bjsoft.loadbalancer.server.port=3000

      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.bjsoft.middlewares=sslheader@swarm

networks:
  network_public:
    external: true
